Se agregó el middleware de validación de archivos.
AlfredoVzla/manejodeasistencias pull request #1
Opened 2023-11-07 03:05 UTC by AlfredoVzla

2023-11-07 04:19 UTC, fcampoa requested changes

2023-11-07 04:19 UTC, fcampoa commented on src/controllers/ControllerAsistencias.js
> +            //res.status(201).json(archivoCargado);
si no ocupas esta linea, borrala, no la dejes comentada

2023-11-07 04:19 UTC, fcampoa commented on src/routers/RouterAsistencias.js
> +    validarCSV(req, res, next);
aqui estás invocando la función, pero no evaluas la respuesta, que pasa aqui si te regresa un 400? falta esa validación

2023-11-10 02:38 UTC, AlfredoVzla commented on src/controllers/ControllerAsistencias.js
> +            //res.status(201).json(archivoCargado);
Ya quedó eso

2023-11-10 02:38 UTC, AlfredoVzla commented on src/routers/RouterAsistencias.js
> +    validarCSV(req, res, next);
Ya quedó también

2023-11-13 01:31 UTC, fcampoa approved these changes

2023-11-14 22:47 UTC, merged