Integración frontend y backend para funcionalizad visualizar(grupo,alumno)
AlfredoVzla/manejodeasistencias pull request #11
Opened 2023-11-23 20:02 UTC by AlfredoVzla

2023-11-24 00:03 UTC, fcampoa requested changes

2023-11-24 00:03 UTC, fcampoa commented on src/public/visualizar.js
> +    const fileContent = document.getElementById('fileContent');
cual es el objetivo de guardar los elementos como tal? o estás tratando de obtener los valores de esos elementos?

2023-11-24 00:03 UTC, fcampoa commented on src/public/visualizar.js
> +    const serverURLAlumno = "http://localhost:8721/consultas/alumno";
las URL las pueden guardar en un archivo general para consultarlas desde ahí, de ese modo, si se cambia el valor de alguna, solo tendría que cambiarse en ese archivo y no en todas las partes donde se use

2023-11-24 01:05 UTC, AlfredoVzla commented on src/public/visualizar.js
> +    const fileContent = document.getElementById('fileContent');
Los utilizo para después acceder a sus valores

2023-11-28 18:57 UTC, fcampoa approved these changes

2023-11-28 19:45 UTC, merged