Desarrollo visualizaciones
AlfredoVzla/manejodeasistencias pull request #5
Opened 2023-11-09 23:31 UTC by Juan-Sotelo

lógica para visualizar asistencias, tanto para un alumno en específico como para las asistencias de un grupo en determinado periodo de tiempo

2023-11-09 23:49 UTC, fcampoa requested changes

2023-11-09 23:49 UTC, fcampoa commented on src/controllers/ControllerConsultas.js
> +            res.status(201).json(consulta);
Porque no encapsular en un enum o en un diccionario los valores de los status? Sería mas dinámico

2023-11-10 00:45 UTC, Juan-Sotelo commented on src/controllers/ControllerConsultas.js
> +            res.status(201).json(consulta);
ya quedó

2023-11-13 01:28 UTC, fcampoa approved these changes

2023-11-14 21:36 UTC, merged